// Draws the favicon, home-screen icons and the link-preview card from the game's own pixel
// art (shared/pixelCard.js: the hero and laptop from src/sprites.js, text in the Ninja
// Adventure 8x8 font). Also writes the font sheet into the card function as base64, so the
// function needs no file of its own at runtime. No dependencies (PNG via node:zlib).
//
//   node scripts/make-images.mjs      rerun after changing the hero or the font
import { readFileSync, writeFileSync } from 'node:fs';
import { Raster, createFont, ogCard, sprite } from '../shared/pixelCard.js';
import { decodePng, encodePng } from '../api/_lib/png.js';

const ROOT = new URL('..', import.meta.url);
const BG = '#0d0d0d';

function writePng(name, img) {
  const png = encodePng(img);
  writeFileSync(new URL(`public/${name}`, ROOT), png);
  console.log(`public/${name}  ${img.width}x${img.height}  ${png.length} bytes`);
}

// Square icon: the hero's inked pixels, centred at a whole-number scale.
function icon(size, scale, bg) {
  const hero = sprite('player_idle');
  const box = hero.ink();
  const img = new Raster(size, size, bg);
  img.draw(hero, Math.round((size - box.w * scale) / 2) - box.x * scale, Math.round((size - box.h * scale) / 2) - box.y * scale, scale);
  return img;
}

const fontPng = readFileSync(new URL('public/assets/ninja/font8x8.png', ROOT));
const font = createFont(decodePng(fontPng));

writePng('favicon-16.png', icon(16, 1));
writePng('favicon-32.png', icon(32, 2));
writePng('apple-touch-icon.png', icon(180, 10, BG));
writePng('icon-192.png', icon(192, 10, BG));
writePng('icon-512.png', icon(512, 26, BG));
writePng('og.png', ogCard(font));

writeFileSync(
  new URL('api/_lib/fontSheet.js', ROOT),
  `// Generated by scripts/make-images.mjs from public/assets/ninja/font8x8.png: the card\n// function's copy of the font sheet, so it reads no file at runtime.\nexport const FONT_PNG_BASE64 =\n  '${fontPng.toString('base64')}';\n`,
);
console.log(`api/_lib/fontSheet.js  ${fontPng.length} bytes of PNG`);
